src/SLBS.Membership.Web/Controllers/UploadsController.cs
using System.Globalization;
using OfficeOpenXml;
using SLBS.Membership.Domain;
using SLBS.Membership.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Member = SLBS.Membership.Web.Models.Member;
using NLog;

namespace SLBS.Membership.Web.Controllers
{
    [SimpleAuthorize(Roles = "Uploader")]
    public class UploadsController : Controller
    {
        private SlsbsContext db = new SlsbsContext();

        private Logger log = LogManager.GetCurrentClassLogger();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Update()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    SafeUpdateMembers(file);
                }
            }

            return View("Mode");
        }

        [HttpPost]
        public ActionResult Load()
        {
            var list = new List<Member>();

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
              

                if (file != null && file.ContentLength > 0)
                {
                    if (file.FileName == "Members.xlsx")
                    {
                        ProcessMembershipFile(file);
                    }
                    if (file.FileName == "PayStatus.xlsx")
                    {
                        UpdatePayStatus(file);
                    }
                    if (file.FileName == "Children.xlsx")
                    {
                        ProcessChildrenFile(file);
                    }
                    if (file.FileName == "ChildrenWithoutMember.xlsx")
                    {
                        ProcessChildrenWithoutMemberFile(file);
                    }
                }
            }

            return View("Mode");
        }

        public ActionResult Show(EnumMode mode)
        {
            var list = new List<Member>();
            if (mode.Equals(EnumMode.Membership))
            {
                list = (List<Member>)Session["MembershipList"];
               
            }
            else if (mode.Equals(EnumMode.BuildingFund))
            {
                list = (List<Member>)Session["BuildingFundList"];
            }
            ViewBag.Mode = mode;
            return View("Show", list);
        }

         private void ProcessChildrenFile(HttpPostedFileBase file)
        {
            using (var package = new ExcelPackage(file.InputStream))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets["Children"];
                for (int row = 4; worksheet.Cells[row, 1].Value != null; row++)
                {
                    var colIndex = 2; //starting column
                    var memberNo = worksheet.Cells[row, colIndex].Value.ToString();

                    if (string.IsNullOrEmpty(memberNo))
                    {
                        continue;
                    }

                    colIndex++;
                    var childName = worksheet.Cells[row, colIndex++].Value.ToString();
                    var level = worksheet.Cells[row, colIndex].Value.ToString() == "senior" ? 10 : int.Parse(worksheet.Cells[row, colIndex].Value.ToString());
                    colIndex++;
                    var ambulanceCover = worksheet.Cells[row, colIndex].Value != null && (worksheet.Cells[row, colIndex].Value.ToString() == "YES");
                    colIndex++;
                    var mediaConsent = worksheet.Cells[row, colIndex].Value != null && (worksheet.Cells[row, colIndex].Value.ToString() == "YES");


                    var existingMember = db.Memberships.SingleOrDefault(i => i.MembershipNumber == memberNo);

                    if (existingMember != null) //member found link kids to this membership
                    {
                        var c = new Domain.Child();
                        c.MembershipId = existingMember.MembershipId;
                        c.IsActive = true;
                        c.FullName = childName;
                        c.MediaConsent = mediaConsent;
                        c.AmbulanceCover = ambulanceCover;
                        c.ClassLevel = (ClassLevelEnum)level;
                        db.Children.Add(c);
                        db.SaveChanges();
                    }

                }

            } 
        }

        private void ProcessChildrenWithoutMemberFile(HttpPostedFileBase file)
        {
            using (var package = new ExcelPackage(file.InputStream))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets["Children"];
                for (int row = 4; worksheet.Cells[row, 1].Value != null; row++)
                {
                    var colIndex = 2; //starting column
                    var memberNo = worksheet.Cells[row, colIndex].Value.ToString();

                    if (string.IsNullOrEmpty(memberNo))
                    {
                        continue;
                    }

                    var existingMember = db.Memberships.SingleOrDefault(i => i.MembershipNumber == memberNo);

                    if (existingMember == null)
                    {
                        //no member found //add dummy member
                        var m = new Domain.Membership();
                        m.MembershipNumber = memberNo;
                        m.ContactName = "Membership added temporarily";
                        db.Memberships.Add(m);
                    }

                    db.SaveChanges();

                }

            }
        }

        private void ProcessMembershipFile(HttpPostedFileBase file)
        {
            using (var package = new ExcelPackage(file.InputStream))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets[SystemConfig.MembershipSheetName];
                var listMembership = new List<Member>();
                var listFathers = new List<Adult>();
                for (int row = 5; worksheet.Cells[row, 1].Value != null; row++)
                {
                    var memberNo = worksheet.Cells[row, 1].Value.ToString();

                    if (string.IsNullOrEmpty(memberNo))
                    {
                        continue;
                    }

                    var existingMember = db.Memberships.SingleOrDefault(i => i.MembershipNumber == memberNo);
                    if (existingMember != null)
                    {
                        continue;
                    }


                    var contactName = worksheet.Cells[row, 2].Value.ToString();
                    var statusString = worksheet.Cells[row, 3].Value.ToString();
                    DateTime? payStatus = null;

                    if (!string.IsNullOrEmpty(statusString))
                    {
                        DateTime payDate;
                        if (DateTime.TryParse(statusString, out payDate))
                        {
                            payStatus = payDate;
                        }
                        //var items = statusString.Split(new[] {'/'});
                    }

                    var m = new Domain.Membership
                    {
                        MembershipNumber = memberNo,
                        ContactName = contactName,
                        PaidUpTo = payStatus
                    };

                    db.Memberships.Add(m);
                    db.SaveChanges();

                    var fathersName = worksheet.Cells[row, 4].Value == null ? null: worksheet.Cells[row, 4].Value.ToString();
                    if (!string.IsNullOrEmpty(fathersName))
                    {
                        var f = new Adult();
                        f.FullName = fathersName;
                        f.MembershipId = m.MembershipId;
                        f.Address = worksheet.Cells[row, 5].Value == null ? null : worksheet.Cells[row, 5].Value.ToString();
                        f.MobilePhone = worksheet.Cells[row, 6].Value == null ? null : worksheet.Cells[row, 6].Value.ToString();
                        f.LandPhone = worksheet.Cells[row, 7].Value == null ? null : worksheet.Cells[row, 7].Value.ToString();
                        
                        f.Email = worksheet.Cells[row, 8].Value == null ? null : worksheet.Cells[row, 8].Value.ToString();

                        f.Role = MembershipRole.Father;

                        db.Adults.Add(f);
                    }
               

                    var mothersName = worksheet.Cells[row, 9].Value == null ? null : worksheet.Cells[row, 9].Value.ToString();

                    if (!string.IsNullOrEmpty(mothersName))
                    {
                        var mother = new Adult();
                        mother.FullName = mothersName;
                        mother.MembershipId = m.MembershipId;
                        mother.Address = worksheet.Cells[row, 10].Value == null ? null : worksheet.Cells[row, 10].Value.ToString();
                        mother.MobilePhone = worksheet.Cells[row, 11].Value == null ? null : worksheet.Cells[row, 11].Value.ToString();
                        mother.LandPhone = worksheet.Cells[row, 12].Value == null ? null : worksheet.Cells[row, 12].Value.ToString();
                        mother.Email = worksheet.Cells[row, 13].Value == null ? null : worksheet.Cells[row, 13].Value.ToString();
                       
                        mother.Role = MembershipRole.Mother;
                        db.Adults.Add(mother);

                    }

                    db.SaveChanges();
                }
            
            } 
        }

        private void SafeUpdateMembers(HttpPostedFileBase file)
        {
            using (var package = new ExcelPackage(file.InputStream))
            {

src/SLBS.Membership.Web/Views/Uploads/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <h2>Update membership details</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h4>Update Payment Status (Monthly Update)</h4>
        <p>
            To update the payment details you need to upload the excel sheet with a pre-defined format. It also needs to follow
            <ul>
                <li>Name        : PayStatus.xlsx</li>
                <li>Sheet Name  : PayStatus</li>
                <li>Header Row  : The first row of the sheet should be column names</li>
                <li>Column Order: Member Number, Name, Payment Status</li>
                <li><a href="../../Templates/PayStatus.xlsx">Download</a> the template file and update for the month and use for the upload</li>
            </ul>
        </p>
    </div>

</div>

<div class="row">

    <div class="col-md-6">
        @using (Html.BeginForm("Load", "Uploads", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" class="btn btn-default" />
            <br/><br/>
            <input type="submit" name="Submit" id="Submit" value="Update Payment Status" class="btn btn-primary" />
        }
    </div>
    
    <div class="col-md-6">
        @using (Html.BeginForm("Update", "Uploads", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" class="btn btn-default" />
            <br /><br />
            <input type="submit" name="Submit" id="Submit" value="Update Member Details" class="btn btn-primary" />
        }
    </div>

</div>

src/SLBS.Membership.Web/Views/Uploads/Mode.cshtml
@using SLBS.Membership.Web.Models
<div class="row">
    <div class="col-md-12">
        <h2>Membership excel loaded. Please select a mode of operation.</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h3>Send Membership Acknowledgement</h3>
        <p><input type="button" value="Send" onclick="location.href='@Url.Action("Show", "Member", new { mode = EnumMode.Membership})'" class="btn btn-primary" /></p>
    </div>
    
    <div class="col-md-6">
        <h3>Send Building Fund Acknowledgement</h3>
        <p><input type="button" value="Send" onclick="location.href='@Url.Action("Show", "Member", new { mode = EnumMode.BuildingFund })'" class="btn btn-primary" /></p>
    </div>
</div>

src/SLBS.Membership.Web/Views/Uploads/SendReport.cshtml
<div class="row">
    <div class="col-md-12">
        <h2>Emails sent successfully to @ViewBag.SentCount members</h2>
    </div>
</div>

src/SLBS.Membership.Web/Views/Uploads/Show.cshtml
@using SLBS.Membership.Web.Models
@model IEnumerable<SLBS.Membership.Web.Models.Member>
           
@section scripts
{
    <script type="text/javascript" >
        $(document).ready(function () {
            $("#toggleAll").click(function () {
                $(".selectMember").prop("checked", $("#toggleAll:checked").length > 0);
                console.log('done');
            });
        });
    </script>
   

}

@using (Html.BeginForm("Send", "Member",   new { mode = @ViewBag.Mode }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12">
            <h3>@ViewBag.Mode Notification</h3>
        </div>
    </div>
   
    <div class="row">
        <div class="col-md-12">
            <h3>
                Found @Model.Count() members who have paid for this cycle
            </h3>
            <p>
                Select the people you'd like to send the notification to and click send.
            </p>
            <input type="submit" name="submit" id="Submit" value="Send" class="btn btn-primary" />
        </div>
    </div>
    
    <br/>
    
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <tr>
                    <th><input type="checkbox" name="selectAll"  id="toggleAll" /></th>
                    <th>
                        @Html.DisplayNameFor(model => model.MemberNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MemberName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Payment)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="selectedMemberNumbers" value="@item.MemberNo" class="selectMember" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MemberNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MemberName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Payment)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
  
}
 