src/SLBS.Membership.Web/Controllers/AdultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using SLBS.Membership.Domain;

namespace SLBS.Membership.Web.Controllers
{
    [Authorize]
    public class AdultsController : Controller
    {
        private SlsbsContext db = new SlsbsContext();

        // GET: Adults
        public async Task<ActionResult> Index()
        {
            var adults = db.Adults.Include(a => a.Membership).Where(a => a.IsActive);
            return View(await adults.ToListAsync());
        }

        // GET: Adults for membership
        [ActionName("Members")]
        [HttpGet]
        public async Task<ActionResult> Membership(int id)
        {
            var adults = db.Adults.Include(a => a.Membership).Where(a => a.MembershipId == id);
            ViewBag.MembershipId = id;
            return View("Index",await adults.ToListAsync());
        }

        // GET: Adults/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            return View(adult);
        }

        // GET: Adults/Create
        [SimpleAuthorize(Roles = "BSEditor")]
        public ActionResult Create(int id)
        {
            ViewBag.MembershipList = new SelectList(db.Memberships, "MembershipId", "MembershipNumber");
            var adult = new Adult()
            {
                MembershipId = id
            };
            return View(adult);
        }

        // POST: Adults/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Create([Bind(Include = "AdultId,MembershipId,FullName,Address,LandPhone,MobilePhone,Email,Role")] Adult adult)
        {
            if (ModelState.IsValid)
            {
                db.Adults.Add(adult);
                await db.SaveChangesAsync();
                return RedirectToAction("Members",new { id = adult.MembershipId});
            }

            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // GET: Adults/Edit/5
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            ViewBag.MembershipId = adult.MembershipId;
            ViewBag.MembershipList = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // POST: Adults/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit([Bind(Include = "AdultId,MembershipId,FullName,Address,LandPhone,MobilePhone,Email,Role")] Adult adult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adult).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Members", new { id = adult.MembershipId });
            }
            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // GET: Adults/Delete/5
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            return View(adult);
        }

        // POST: Adults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Adult adult = await db.Adults.FindAsync(id);
            adult.IsActive = false;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SLBS.Membership.Web/Controllers/ChildrenController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using SLBS.Membership.Domain;

namespace SLBS.Membership.Web.Controllers
{
    [Authorize]
    [Route("Children")]
    public class ChildrenController : Controller
    {
        private SlsbsContext db = new SlsbsContext();

        // GET: Children
        public async Task<ActionResult> Index()
        {
            var children = db.Children.Include(c => c.Membership).Include(c => c.Comments).Where(c => c.IsActive);
            return View(await children.ToListAsync());
        }
        
        // GET: Children for membership
        [ActionName("Members")]
        public async Task<ActionResult> Membership(int id)
        {
            var children = db.Children.Include(c => c.Membership).Where(i => i.MembershipId == id);
            ViewBag.MembershipId = id;
            return View("Index",await children.ToListAsync());
        }

        // GET: Children/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Child child = await db.Children.Include(c => c.Comments).SingleOrDefaultAsync(c => c.ChildId == id && c.IsActive);
            if (child == null)
            {
                return HttpNotFound();
            }
            return View(child);
        }

        // GET: Children/Create
        [SimpleAuthorize(Roles = "DSEditor")]
        public ActionResult Create(int? id)
        {
            ViewBag.MembershipList = new SelectList(db.Memberships, "MembershipId", "MembershipNumber");
            var child = new Child();
            if (id.HasValue)
            {
                child.MembershipId = id.Value;
            }
            return View(child);
        }

        // POST: Children/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "DSEditor")]
        public async Task<ActionResult> Create([Bind(Include = "ChildId,MembershipId,FullName,ClassLevel,MediaConsent,AmbulanceCover")] Child child)
        {
            if (ModelState.IsValid)
            {
                db.Children.Add(child);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", child.MembershipId);
            return View(child);
        }

        // GET: Children/Edit/5
         [SimpleAuthorize(Roles = "DSEditor")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Child child = await db.Children.FindAsync(id);
            if (child == null)
            {
                return HttpNotFound();
            }
            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", child.MembershipId);
            return View(child);
        }

        // POST: Children/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "DSEditor")]
        public async Task<ActionResult> Edit([Bind(Include = "ChildId,MembershipId,FullName,ClassLevel,MediaConsent,AmbulanceCover")] Child child)
        {
            if (ModelState.IsValid)
            {
                db.Entry(child).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", child.MembershipId);
            return View(child);
        }

        // GET: Children/Delete/5
         [SimpleAuthorize(Roles = "DSEditor")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Child child = await db.Children.FindAsync(id);
            if (child == null)
            {
                return HttpNotFound();
            }
            return View(child);
        }

        // POST: Children/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "DSEditor")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Child child = await db.Children.FindAsync(id);
            child.IsActive = false;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("AddComment")]
        public JsonResult AddComment(ChildComment childComment)
        {
            Child child = db.Children.Find(childComment.ChildId);
            childComment.CreatedOn = System.DateTime.Now;
            child.Comments.Add(childComment);

            db.SaveChanges();

            return Json(new { result = "OK" });
        }

        [HttpPost, ActionName("DeleteComment")]
        public JsonResult DeleteComment(int commentId)
        {
            var comment = db.ChlidComments.Find(commentId);
            db.ChlidComments.Remove(comment);
            db.SaveChanges();

            return Json(new { result = "OK" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SLBS.Membership.Web/Views/Children/Create.cshtml
@model SLBS.Membership.Domain.Child

@{
    ViewBag.Title = "Create";
    var membershipList = (SelectList)ViewBag.MembershipList;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Child</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MembershipId, "MembershipId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.MembershipId, membershipList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MembershipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ClassLevel, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediaConsent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MediaConsent)
                    @Html.ValidationMessageFor(model => model.MediaConsent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmbulanceCover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AmbulanceCover)
                    @Html.ValidationMessageFor(model => model.AmbulanceCover, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SLBS.Membership.Web/Views/Children/Delete.cshtml
@model SLBS.Membership.Domain.Child

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Child</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership.MembershipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaConsent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaConsent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmbulanceCover)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmbulanceCover)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/SLBS.Membership.Web/Views/Children/Details.cshtml
@model SLBS.Membership.Domain.Child

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Child</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership.MembershipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaConsent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaConsent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmbulanceCover)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmbulanceCover)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ChildId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<hr/>

@{
    Html.RenderPartial("_Comments", Model.Comments);
}

<script>

    function addComment() {

        var postData = { ChildId: '@Model.ChildId', Comment: $("#comment").val(), CreatedBy: $("#createdBy").val()};

        jQuery.noConflict();
        $('#commentModal').modal('hide');

        $.ajax({
            url: "@Url.Action("AddComment","Children")",
            type: 'POST',
            data: JSON.stringify(postData),
            dataType: 'json',
            contentType: 'application/json',
            success: function () {
                console.log('added');
                location.reload();

            },
            error: function () { alert("Error adding note");}
        });

    }

    function removeComment(commentId) {
        console.log(commentId);
        var postData = { commentId: commentId };

          $.ajax({
            url: "@Url.Action("DeleteComment","Children")",
            type: 'POST',
            data: JSON.stringify(postData),
            dataType: 'json',
            contentType: 'application/json',
            success: function () {
                console.log('removed');
                location.reload();

            },
            error: function () { alert("Error adding note");}
        });
    }

</script>

src/SLBS.Membership.Web/Views/Children/Edit.cshtml
@model SLBS.Membership.Domain.Child

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Child</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ChildId)

        <div class="form-group">
            @Html.LabelFor(model => model.MembershipId, "Membership", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MembershipId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MembershipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ClassLevel, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediaConsent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MediaConsent)
                    @Html.ValidationMessageFor(model => model.MediaConsent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmbulanceCover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AmbulanceCover)
                    @Html.ValidationMessageFor(model => model.AmbulanceCover, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SLBS.Membership.Web/Views/Children/Index.cshtml
@model IEnumerable<SLBS.Membership.Domain.Child>

@{
    ViewBag.Title = "Index";
}

<h2>Children</h2>

<p>
    @Html.ActionLink("Create New", "Create",new { id = ViewBag.MembershipId })
</p>
<table class="table-striped" id="childTable" style="width: 100%;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClassLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MediaConsent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmbulanceCover)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Membership.PaidUpTo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var className = item.IsActive ? "" : "text-muted";
            <tr style="height: 30px" class="@className">
                <td>
                    @Html.DisplayFor(modelItem => item.Membership.MembershipNumber)
                </td>
                <td>
                    <span>
                    @Html.DisplayFor(modelItem => item.FullName)
                    @{ 
                        if (item.Comments.Any())
                        {
                            <i class="fa fa-sticky-note-o" aria-hidden="true" title="Click details to see notes"> <mark>N</mark></i>
                        }
                    }
                     </span>

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassLevel)
                </td>
                <td>
                    @if (item.MediaConsent.HasValue && item.MediaConsent.Value)
                    {
                        <span>YES</span>
                    }
                    else
                    {
                        <span>NO</span>
                    }
                </td>
                <td>
                    @if (item.AmbulanceCover.HasValue && item.AmbulanceCover.Value)
                    {
                        <span>YES</span>
                    }
                    else
                    {
                        <span>NO</span>
                    }
                </td>
                <td>
                   @(item.Membership.PaidUpTo.HasValue ? item.Membership.PaidUpTo.Value.ToString("MMM/yy") : "-")
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ChildId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ChildId }) |
                    @Html.ActionLink("Parents", "Members", "Adults", new { id = item.MembershipId }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ChildId })
                </td>
            </tr>
        }
    </tbody>

</table>
@Html.AntiForgeryToken()


<script>

    $(document).ready(function () {
        $('#childTable').DataTable({
            stateSave: true,
            columnDefs: [
                {
                    orderable: false,
                    targets: 4
                },
                {
                     orderable: false,
                     targets: 3
                }
            ],
            select: {
                style:    'os',
                selector: 'td:first-child'
            },
            order: [[ 2, 'asc' ]]
        });
    });

    function addAntiForgeryToken(data) {
        data.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
        return data;
    };

   

    function allSelect() {
        console.log('all');
        if ($("#allMemberSelect").hasClass('allChecked')) {
            $('input[type="checkbox"]').prop('checked', false);
        } else {
            $('input[type="checkbox"]').prop('checked', true);

        }
        $("#allMemberSelect").toggleClass('allChecked');

    }

    function showSuccess(message) {
        $("#userMessage").html(message);
    }

    function showError(message) {
        $("#errorMessage").html(message);
    }
</script>

src/SLBS.Membership.Web/Views/Children/_Comments.cshtml
@model IEnumerable<SLBS.Membership.Domain.ChildComment>


<h4>Membership Notes</h4>

<table class="table-striped" id="memberCommentTable" style="width: 100%;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr style="height: 30px">
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    <a href="#" onclick="removeComment(@item.ChildCommentId)">Remove</a>
                </td>
            </tr>
        }
    </tbody>

</table>

<p>
    <button type="button" data-toggle="modal" data-target="#commentModal" class="btn btn-primary">Add note</button>
</p>

<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">New Note</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Note entered by:</label>
                        <input type="text" class="form-control" id="createdBy">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">Note:</label>
                        <textarea class="form-control" id="comment"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="addComment()">Save</button>
            </div>
        </div>
    </div>
</div>