src/SLBS.Membership.Web/Controllers/AdultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using SLBS.Membership.Domain;

namespace SLBS.Membership.Web.Controllers
{
    [Authorize]
    public class AdultsController : Controller
    {
        private SlsbsContext db = new SlsbsContext();

        // GET: Adults
        public async Task<ActionResult> Index()
        {
            var adults = db.Adults.Include(a => a.Membership).Where(a => a.IsActive);
            return View(await adults.ToListAsync());
        }

        // GET: Adults for membership
        [ActionName("Members")]
        [HttpGet]
        public async Task<ActionResult> Membership(int id)
        {
            var adults = db.Adults.Include(a => a.Membership).Where(a => a.MembershipId == id);
            ViewBag.MembershipId = id;
            return View("Index",await adults.ToListAsync());
        }

        // GET: Adults/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            return View(adult);
        }

        // GET: Adults/Create
        [SimpleAuthorize(Roles = "BSEditor")]
        public ActionResult Create(int id)
        {
            ViewBag.MembershipList = new SelectList(db.Memberships, "MembershipId", "MembershipNumber");
            var adult = new Adult()
            {
                MembershipId = id
            };
            return View(adult);
        }

        // POST: Adults/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Create([Bind(Include = "AdultId,MembershipId,FullName,Address,LandPhone,MobilePhone,Email,Role")] Adult adult)
        {
            if (ModelState.IsValid)
            {
                db.Adults.Add(adult);
                await db.SaveChangesAsync();
                return RedirectToAction("Members",new { id = adult.MembershipId});
            }

            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // GET: Adults/Edit/5
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            ViewBag.MembershipId = adult.MembershipId;
            ViewBag.MembershipList = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // POST: Adults/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit([Bind(Include = "AdultId,MembershipId,FullName,Address,LandPhone,MobilePhone,Email,Role")] Adult adult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adult).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Members", new { id = adult.MembershipId });
            }
            ViewBag.MembershipId = new SelectList(db.Memberships, "MembershipId", "MembershipNumber", adult.MembershipId);
            return View(adult);
        }

        // GET: Adults/Delete/5
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adult adult = await db.Adults.FindAsync(id);
            if (adult == null)
            {
                return HttpNotFound();
            }
            return View(adult);
        }

        // POST: Adults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Adult adult = await db.Adults.FindAsync(id);
            adult.IsActive = false;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SLBS.Membership.Web/Controllers/MembershipsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using SLBS.Membership.Domain;
using NLog;

namespace SLBS.Membership.Web.Controllers
{
    [Authorize]
    public class MembershipsController : Controller
    {
        private SlsbsContext db = new SlsbsContext();

        private Logger log = LogManager.GetCurrentClassLogger();

        // GET: Memberships
        [SimpleAuthorize(Roles = "BSEditor,Viewer")]
        public async Task<ActionResult> Index()
        {
            log.Debug("Loading members");
            return View(await db.Memberships.ToListAsync());
        }

        // GET: Memberships/Details/5
        [SimpleAuthorize(Roles = "BSEditor,Viewer")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var membership = await db.Memberships.FindAsync(id);
            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        // GET: Memberships/Create
        [SimpleAuthorize(Roles = "BSEditor")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Memberships/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Create([Bind(Include = "MembershipNumber,ContactName,PaidUpTo,ApplicationDate,BlockEmails")] Domain.Membership membership)
        {
            var memberKey = membership.MembershipNumber;
            if (!Char.IsLetter(memberKey, 0))
            {
                ModelState.AddModelError("MembershipNumber", "Please provide a letter for membership key");
            }

            if (ModelState.IsValid)
            {
                membership.MembershipNumber = GenerateMembershipNumber(memberKey.ToUpper());
                db.Memberships.Add(membership);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(membership);
        }

        private string GenerateMembershipNumber(string membershipKey)
        {
            var memberNumbers = db.Memberships.Where(m => m.MembershipNumber.StartsWith(membershipKey)).Select(m => m.MembershipNumber).ToList();
            
            if (!memberNumbers.Any()) return string.Format("{0}0001", membershipKey);

            var memberNumberOrdered = memberNumbers.Select(m => int.Parse(m.Remove(0, 1))).OrderByDescending(m => m).ToList();

            var latestMember = memberNumberOrdered.First();

            return string.Format("{0}{1}", membershipKey, (latestMember + 1).ToString("D4"));

        }

        // GET: Memberships/Edit/5
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var membership = await db.Memberships.FindAsync(id);
            //var comments = await db.Memberships
            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        // POST: Memberships/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> Edit([Bind(Include = "MembershipId,MembershipNumber,ContactName,PaidUpTo,ApplicationDate,BlockEmails")] Domain.Membership membership, string comment)
        {
            if (ModelState.IsValid)
            {
                var membershipComment = new MembershipComment();
                membershipComment.Comment = comment;
                membershipComment.CommentedOn = DateTime.Now;
                membershipComment.StatusUpdatedOn = DateTime.Now;
                membershipComment.MembershipId = membership.MembershipId;

                membership.MembershipComments.Add(membershipComment);

                db.Entry(membership).State = EntityState.Modified;
                db.Entry(membershipComment).State = EntityState.Added;

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(membership);
        }

        // GET: Memberships/Delete/5
        [SimpleAuthorize(Roles = "Admin,BSEditor")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var membership = await db.Memberships.FindAsync(id);
            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        // POST: Memberships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "BSEditor")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var membership = await db.Memberships.FindAsync(id);
            db.Memberships.Remove(membership);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("SaveSendList")]
        [ValidateAntiForgeryToken]
        [SimpleAuthorize(Roles = "Sender")]
        public async Task<ActionResult> SaveSendList(List<int> ids)
        {
            Session["SelectedMemberIds"] = null; //clear
            Session["SelectedMemberIds"] = ids;
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SLBS.Membership.Web/Views/Adults/Create.cshtml
@model SLBS.Membership.Domain.Adult

@{
    ViewBag.Title = "Create";
    var membershipList = (SelectList)ViewBag.MembershipList;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MembershipId, "MembershipId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.MembershipId, membershipList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MembershipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobilePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LandPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LandPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LandPhone, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Role, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SLBS.Membership.Web/Views/Adults/Delete.cshtml
@model SLBS.Membership.Domain.Adult

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Adult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership.MembershipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobilePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobilePhone)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.LandPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LandPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        


        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/SLBS.Membership.Web/Views/Adults/Details.cshtml
@model SLBS.Membership.Domain.Adult

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Adult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membership.MembershipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobilePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobilePhone)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.LandPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LandPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AdultId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/SLBS.Membership.Web/Views/Adults/Edit.cshtml
@model SLBS.Membership.Domain.Adult

@{
    ViewBag.Title = "Edit";
    var membershipList = (SelectList)ViewBag.MembershipList;
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AdultId)

        <div class="form-group">
            @Html.LabelFor(model => model.MembershipId, "MembershipId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.MembershipId, membershipList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MembershipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobilePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LandPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LandPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LandPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Role, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Members", new { id = ViewBag.MembershipId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SLBS.Membership.Web/Views/Adults/Index.cshtml
@model IEnumerable<SLBS.Membership.Domain.Adult>

@{
    ViewBag.Title = "Adults";
}

<h2>Adults</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.MembershipId }) | 
    @Html.ActionLink("Back to Memberships","Index","Memberships")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Membership.MembershipNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MobilePhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LandPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Role)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    var className = item.IsActive ? "" : "text-muted";

    <tr class="@className">
        <td>
            @Html.DisplayFor(modelItem => item.Membership.MembershipNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MobilePhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LandPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AdultId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AdultId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AdultId })
        </td>
    </tr>
}
</table>